### PR TITLE
sites compatibility

### PR DESCRIPTION
**Pull request by reepush**
Fixed compatibility issues for sites:
* ldlc.ch
* techmania.ch
* evernote.com
* tripadvisor.com

Auth works by manual testing. @mosaadm take a look if we should fix our automated tests.

### CODE REVIEW

**Comment by reepush** [comment]
pc-ostschweiz.ch also works with manual testing
@limpkin I will move these tests to CIFails suite, so we can easier see that should be checked

**Comment by limpkin** [comment]
@reepush no need to recategorize them. @mosaadm can keep track.

**Comment by mosaadm** [comment]
@reepush I just tried the 4 websites. The behaviour is the same manually and in the automated tests:

- ldlc does not seem to work for me. The username and password are written by mooltipass but the user does not actually login. The page is just refreshed.  

- techmania and tripadvisor are still failing
- evernote seems to work

**Comment by limpkin** [comment]
@reepush I'm **extremely** surprised to see your recent PR given @mosaadm comments.

**Comment by reepush** [comment]
@mosaadm for ldlc.ch I see that we can't check that user is logged in because site redirects us to another page comparing with the first time login

[I made a video, take a look](https://www.dropbox.com/s/59adelfc89gj5x2/ldlc-test.mp4?dl=0)

**Comment by mosaadm** [comment]
@reepush It doesnot matter because the user is still not logged in. If you hover the mouse over the log in you will see that there is still a login (i think its "s'connecter" in french). This means that the user is currently not logged in.

**Comment by reepush** [comment]
@mosaadm let's move to #469 pull request and make further progress on sites compatibility

**Pull request merged**
