### PR TITLE
Use FreeSans as font for the (serial number) labels

### PR DESCRIPTION
**Pull request by pklaus**
- [x ] This PR is compliant with the contributing guidelines
- [x ] The PR text includes a **detailed explanation**
- [x ] I have thoroughly tested my contribution.

This pull request changes the font used for the label generation in `tools/_python_framework/png_labels.py`. Instead of Helvetica, the very similar FreeSans is being used. It is part of [GNU FreeFont ](https://www.gnu.org/software/freefont/)and can be distributed freely under the terms of the GPLv3+.

The positioning of the text was slightly adjusted to the new font so that the labels look very much like they used to do with the old font.

### CODE REVIEW

**Comment by limpkin** [comment]
Hey there,

Thanks a lot for the PR! just to be 100% sure, could you send here a picture of the 2 different labels, printed?

Thanks,
Mathieu

**Comment by pklaus** [comment]
I'll do that. For now, I have a preview of how the label image looks like:

Old font (Helvetica):
label1_17x87_mpm-red-54321 helvetica
New font (FreeSans):
label1_17x87_mpm-red-54321 freesans

I will also print them both and attach a picture, this will take me another 30 minutes though.

**Comment by limpkin** [comment]
Thanks!

FYI the code to generate our labels is here: https://github.com/limpkin/mooltipass/blob/master/tools/_python_framework/mooltipass_mass_prod_init_proc.py#L179

**Comment by pklaus** [comment]
Well, actually all you need to change is in this pull request, because in [line 21 of the file you stated](https://github.com/limpkin/mooltipass/blob/master/tools/_python_framework/mooltipass_mass_prod_init_proc.py#L21) you import from png_labels.py changed in this pull request.

Here is a photo of the two labels: The upper one with the Helvetica font, the lower one with the FreeSans font.



------------

I also tested the second label type. Here it is with the Helvetica font:

label2_17x87_mpm-v1-8mb-red-12345 helvetica
And with the new FreeSans font:
label2_17x87_mpm-v1-8mb-red-12345 freesans

The printout looks like this:

**Comment by limpkin** [comment]
Thanks a lot for the pictures!

Actually if I mentioned the lines of code it was so you could print the very same labels we print (which are very slightly different than the ones you show here).

Anyway everything looks good... thanks a lot!

**Pull request merged**
