### PR TITLE
Bootloaderfix2

### PR DESCRIPTION
**Pull request by NicoHood**
Supersedes https://github.com/limpkin/mooltipass/pull/192

Delay difference (micros +-4):
Original:
6328
New:
10060

### CODE REVIEW

**Comment by limpkin** [comment]
AES_KEY_LENGTH/8 = 256 / 8 = 32, sizeof(temp_data) = 16.
And I do love my comment style.

**Comment by NicoHood** [comment]
Huh?
It is a good practice to use the size of the destination instead of the source. I know that those are equal for sure.

For the comment style:
But then do it always the same and not mixed

What about the delay? This is may more clear and should use the same code size.

**Comment by limpkin** [comment]
read again... the if is run more than once.

The delay... well can be implemented. but it's more "fine touches" at this point

**Comment by NicoHood** [comment]
Oh you are right about the If.

Sure the rest is fine touch. But its to read and understand it better. And since you wanted to make the bootloader as simple as possible this would be more clearer as you have a clear ms value instead of just a loop count.

And for the style: I thought there was a style guide? I do not really care about /**/ or // (even though I prefer //) but it should then be the same for the whole file.

Should I remove the single commit or will you cherry-pick the others?

**Comment by limpkin** [comment]
well the PR is already closed so I can make the changes....

**Comment by NicoHood** [comment]
You can reopen...

**Pull request closed without merging**
