### PR TITLE
HTTP Login Update

### PR DESCRIPTION
**Pull request by Gastonius**
Http and https logins now working again.

While I kept the "event" variable, I renamed it to mooltipassEvent. It is recommended to migrate all uses of event. to mooltipassEvent in the near future.

### CODE REVIEW

**Comment by limpkin** [comment]
is it tested?

**Comment by Gastonius** [comment]
Just in a couple of sites. It works for me. Both in HTTP and HTTPS. Don't
have many sites to test tho.

**Comment by limpkin** [comment]
I mean, are you sure you didn't break anything by renaming "events"? :)

**Comment by Gastonius** [comment]
No, while I renamed it, I also kept the "event" var as a reference

**Comment by Gastonius** [comment]
Would you feel better if I perform a full test?

**Comment by limpkin** [comment]
no it's alright! just wanted to make sure that this rename didn't break anything

**Comment by Gastonius** [comment]
Actually, the EVENT was breaking the HTTP AUTH (because of a custom Event
named "event" in the global scope)

**Comment by limpkin** [comment]
oh that's quite interesting!
thanks

**Pull request merged**
