### PR TITLE
<firefox_extension: Only create WebExtension>

### PR DESCRIPTION
**Pull request by bobsaintcool**
I was wrong trying to build Firefox add-on by providing install.rdf.
Move back to WebExtension based on manifest.json and change the
updateCleanVersion to perform some check before creating the XPI
tarball.

Fixes ce7296ff5876c7d0baf6d4ca0ea5abc3bd3f45b9

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [x] This PR is compliant with the contributing guidelines (if not, please describe why): code is fully documented and if possible a .md file is made.
- [x] The PR text includes a **detailed explanation** (more than 50 chars)
- [ ] I have thoroughly tested my contribution.

This revert some modification on the kind of extension upload to the Firefox store from add-ons (with install.rdf) to WebExtension with manifest.json. The former will deprecated at the end of 2017.

### CODE REVIEW

**Comment by limpkin** [comment]
Thanks for the PR!

Why is the last box not checked? :(

**Comment by limpkin** [comment]
it seems your xpi is simply a renamed .zip... if that is the case, could you also only generate a .zip for the chromium output? this way we don't need to do it manually.
Thanks!

**Comment by bobsaintcool** [comment]
> Why is the last box not checked? :(

I still have some problem with my firmware so moolticute does not work great lead to difficulties to test the function of the extension on firefox.

> it seems your xpi is simply a renamed .zip... if that is the case, could you also only generate a .zip for the chromium output? this way we don't need to do it manually

Yes it is (was). I was based on this XPI spec[0], for now a base ZIP file is created.
  * For Firefox XPI its still a simple symlink with an extension in .xpi
  * For Chromium is integrated the CRX build for Chrome[1]

[0] https://developer.mozilla.org/en-US/docs/Mozilla/XPI
[1] https://developer.chrome.com/extensions/crx

**Comment by limpkin** [comment]
sorry to be a bother, but could you make another option for firefox or chrome to simply generate a .zip file? Maybe for each build output, specify a "native" or "zip" archive output?

**Comment by bobsaintcool** [comment]
For now: both the .zip, .xpi (unsigned) and .crx (signed) is generated. For that we have to provided the signing key with --sign-key.

Soon I will update to that every --target could have an --sign-key

**Comment by bobsaintcool** [comment]
The script must be more simple now:
* without argument, only a zip file is created (note that everything that was related as specific for Firefox is not copied at that point)
* the --target <TARGET> allows to create packaged extension for a specific target chrome/chromium (CRX file format), firefox (XPI). This switch could be used any number we wants to build different packages at once. This switch requires the use of --sign-key for every --target issued.

At that time, generating a signed XPI is not supported (the the --sign-key is not very useful for firefox, but still required). I may have some reading to understand how to sign this properly.

```
# only create the zip
$ updateCleanVersion.sh 

# only CRX
$ updateCleanVersion.sh --target chromium --sign-key ./chromium.key
$ updateCleanVersion.sh --target chrome --sign-key ./chromium.key

# only XPI
$ updateCleanVersion.sh --target firefox --sign-key ./firefox.key

# both XPI and CRX
$ updateCleanVersion.sh --target chromium --sign-key ./chromium.key --target firefox --sign-key ./firefox.key

# little help
$ updateCleanVersion.sh  --help
```

Finally I changed a part of the google provided script by replacing an ls with a find. The former should not be used in script.

**Pull request merged**
