### PR TITLE
ensure that content script is ready for http auth

### PR DESCRIPTION
**Pull request by reepush**

### CODE REVIEW

**Comment by reepush** [comment]
By these changes we don't show popup for firefox, but it's possible to authorize still.
Will create issue for HTTP Auth. We need to find good solution for it.

**Comment by limpkin** [comment]
"We need to find good solution for it." >> this sounds like an issue that will be created on our repository that will never be addressed. 
**This is TOTALLY not acceptable.**

**Comment by reepush** [comment]
I have created issue #468 to investigate this problem across all browsers. This is a quick fix because of emergency.

**Comment by limpkin** [comment]
i'm merging but i really hope we change this asap.

**Pull request merged**
