### PR TITLE
Update font_profont_10_72dpi.h

### PR DESCRIPTION
**Pull request by RTivy**
Fix bitmaps for !, ', and | ascii chars

### CODE REVIEW

**Comment by CEngen1** [comment]
RTivy is a friend of mine I asked him to help us since Darran / Harlequin went AWOL some time ago.  
He explained what he did here: 

The fonts in font_profont_10_72dpi.h are messed up for the ! and ' and | bitmaps (or glyphs). I can see why they're printing what they are. For instance, the font bitmap for the | char is:
const uint8_t profont_10_72_0x7c[] attribute((progmem)) = { /* '|' width: 6 / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0xc0, / [] */ 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] */ 
};

The bitmap shown in the comments shows the single pixel in the middle of the glyph, and the setting of 0x00s in the rows with the single 0xc0 in a middle row matches that.

Same for the !, it's all 0x00s:
const uint8_t profont_10_72_0x21[] attribute((progmem)) = { /* '!' width: 6 / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] / 
};
and the ', all 0x00s:
const uint8_t profont_10_72_0x27[] attribute((progmem)) = { / ''' width: 6 / 
0x00, / [ ] / 
0x00, / [ ] / 
0x00, / [ ] */ 
};
That's why they're blank.

Now, I'm not sure what they should be, since I can't quite decode the bitmap values (not sure what the . and * are in the comments for the glyph 'rows'), but looking at other chars gives a hint. For instance, the [ char is close to the |. Since the [ char is:
const uint8_t profont_10_72_0x5b[] attribute((progmem)) = { /* '[' width: 6 / 
0xf0, / [] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xf0, / [] */ 
};
then that tells me we could get | by changing the top & bottom 0xf0 to 0xc0.

So, change the corresponding arrays in the file font_profont_10_72dpi.h with these 3:
const uint8_t profont_10_72_0x7c[] attribute((progmem)) = { /* '|' width: 6 / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] */

};

A ' is close to a |, maybe just the top 3 rows, so it could be:
const uint8_t profont_10_72_0x27[] attribute((progmem)) = { /* ''' width: 6 / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] */ 
};

And a ! is close to |, but not as tall and with a blank row on line up from the bottom, and a little fatter up top:
const uint8_t profont_10_72_0x21[] attribute((progmem)) = { /* '!' width: 6 / 
0x00, / [ ] / 
0xf0, / [] / 
0xf0, / [] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0xc0, / [* ] / 
0x00, / [ ] / 
0xc0, / [* ] / 
0x00, / [ ] */
};

Those are crude replacements, and I could try to make better glyphs for you with some more time, but this is what I could determine and come up with in 30 minutes.

You can view, comment on, or merge this pull request online at:
  https://github.com/limpkin/mooltipass/pull/142

Commit Summary
Update font_profont_10_72dpi.h
File Changes
M arduino/libraries/oledmp/font_profont_10_72dpi.h (40)
Patch Links:
https://github.com/limpkin/mooltipass/pull/142.patch
https://github.com/limpkin/mooltipass/pull/142.diff



- Charlie

**Comment by RTivy** [comment]
I just manually filled in the pixels in the header file.  I figured there was some autogeneration tool but I'm just jumping in to this project to help Charlie E.  I don't even know how it gets built for the firmware.  Please let me whether or not they render.

I don't think the glyph widths need changing.  I assumed that the existing array inits for ! ' and | had the right number of bytes (that were mostly 0x00) so I just changed the values, and the glyph table at the end seemed to be correct.

**Comment by jnwatts** [comment]
Yup, you're quite right about the widths: We found the root of the problem yesterday morning. The width/height/etc were all correct, but the code that reads pixel data didn't properly handle a glyph with width equal to 1. It's fixed now and the auto-generation works correctly :-)

**Comment by RTivy** [comment]
Just saw your response, thanks.

I'm still getting used to GitHub dynamics.

**Comment by jnwatts** [comment]
No worries :-)

**Comment by CEngen1** [comment]
Thanks RTivy and JNWatts 
:)
Charlie

**Pull request merged**
