### PR TITLE
Fixed left login scroll overview for non alphabetic characters

### LINKED ISSUE #266: [Mini Firmware] Login list alphabet wrong on the left side
### Expected behavior
If you enter the login list the left side shows the current character (e.g. A) and the previous and next above or beloow.

### Actual behavior
This does work fine with normal letters (a-z) but not for special characters.

### Step by step guide to reproduce the problem
Add credential with names 1,2,3,4,5,6,7, a and scrol though the login list. On the left is the next character wrong. It always says "A" instead of 2 if you selected 1.

### Mooltipass version
v0.7 (current master) but self compiled for MP Mini

### PR DESCRIPTION
**Pull request by NicoHood**
Fixes #266
- [X] This PR is compliant with the contributing guidelines (if not, please describe why): code is fully documented and if possible a .md file is made.
- [X] The PR text includes a **detailed explanation** (more than 50 chars)
- [X] I have thoroughly tested my contribution.

This fixes the left size scrol overview for the login. Before a lookup table for the first letter and the corresponding node was used. However this does not take services into account which start with 0-9 or special characters such as $%&?! etc.

The PR tries to reimplement this feature without a LUT at minimum cost. It is also compatible with the fast skipping of letters by holding the wheel while scrolling.
### Tests made:
- A single entry
- Two entries
- 3-10 entries
- special characters before a (! etc)
- numbers before a (0)
- special chars after z (~ etc)
- normal scrol
- press + scroll
### Code size deltas

Its probably less for your build and could still fit. Even if we use other workarounds, I think the overhead will be kept the same mostly.

```
// Before (with the unoptimized linux makefile)
Program:   28796 bytes (87.9% Full)
// After (with the unoptimized linux makefile)
Program:   28882 bytes (88.1% Full)
+86

// Before (optimized linux makefile)
Program:   28644 bytes (87.4% Full)
// After (optimized linux makefile)
Program:   28722 bytes (87.7% Full)
+78
```

### CODE REVIEW

**Comment by limpkin** [comment]
we are NOT going to loop through all credentials in the external flash to get to the next letter, as this will take way too much time for large DBs.

**Comment by NicoHood** [comment]
I've just noticed that I do use credentials with numbers. More detailed I use them for my HDDs: 2,5" hdd or 500GB hdd etc. So we somehow need a way to also display those. I'd aggree that this is a bit oversized if you also use special characters, but limitations are always bad.

The note about large databases is correct. However I've imported my own which DOES has a lot of entries and its super fast. Even for skipping to the next character.

As an optimization we could start searching from the current parent node to the next nodes. Then the number of nodes to iterate through is still extremely fast except you have 500 entries starting with the current letter selected. I dont see speed problems, but I will possible build a large database where I can test this better (can do this next week).

**Comment by limpkin** [comment]
"The note about large databases is correct. However I've imported my own which DOES has a lot of entries and its super fast. ": once again, as previously mentioned, if you want a PR to be approved you will want to actually prove us with **real** measurements that it's still "super fast"

**Comment by NicoHood** [comment]
Note to myself: `upper()` should be moved to utils.c. thats possibly a better place.

**Comment by NicoHood** [comment]
I've tested my function now with the following setup:

```c
// include interrupts.h and add -DENABLE_MILLISECOND_DBG_TIMER as compiler flag
            uint32_t m = millis();

            // Display first letters
            getPreviousNextFirstLetterForGivenLetter(current_fchar, fchar_array, prev_next_fletter_parents_addr);
            displayCenteredCharAtPosition(fchar_array[0], 5, 1, FONT_8BIT16);
            displayCenteredCharAtPosition(fchar_array[1], 5, 6, FONT_PROFONT_14);
            displayCenteredCharAtPosition(fchar_array[2], 5, 26, FONT_8BIT16);
            miniOledFlushEntireBufferToDisplay();

            uint32_t m2 = millis();
            char buffer [33];
            int_to_string (m2-m,buffer);
            miniOledPutstrXY(15, 0, OLED_LEFT, buffer);

            int_to_string (prev_next_fletter_parents_addr[0], buffer);
            miniOledPutstrXY(30, 2, OLED_LEFT, buffer);
            int_to_string (prev_next_fletter_parents_addr[1], buffer);
            miniOledPutstrXY(30, 2+8, OLED_LEFT, buffer);
            int_to_string (prev_next_fletter_parents_addr[2], buffer);
            miniOledPutstrXY(30, 2+16, OLED_LEFT, buffer);
            miniOledFlushEntireBufferToDisplay();
```

The times for my first commit is 7-X ms. The closer you get to the end, the higher the latency gets. For my database the maximum was 50ms. 50ms is absolutely no problem for my database like that. However that sounds too long to me if you have a larger database.

My second try searches from the current selected credential as base (backwards and farward). This gives me lower latency but a more complex code. However I could shrink down the additional delta to +30 bytes on top of my previous fix. It took me very long to get there, before I had +150. The time delay for each entry of my database is 6-17 maximum. This is especially the case for "a" entries, as I have many of them. I am really happy with this result, that is the best we can get without a LUT.

But how fast is the lookup table? And do we even need it?
The lookup table has a pretty constant delay of 5ms. Its faster, but the bug appears with the LUT.
Looking further in the code shows `getParentNodeForLetter()` is the only function (at least from what i've seen) that uses the LUT. Its used for some credentials searching. We could possibly use a slowe forward search for this function which I already implemented in my 2nd fix. Then we have a lot of flash left. But I am unsure if thats good, you should know that.

**Comment by limpkin** [comment]
That is indeed too long.
The look up table is to speed up the password retrieval process when using the chrome/ff extension.

**Comment by NicoHood** [comment]
Too long for what? For the extension the LUT is still used. But not for the login menu. I could not see any difference with 50ms. And with the update 17ms is now even better. To get back a delay of 50ms I need to have as many "a" entries as i currently have on the whole device. And even then it would not be a problem.

If we don't use my proposed method I have no idea how to fix it else. I've read on wiki etc about linked list and optimized search and beside additional overhead there is also no real better idea than the LUT itself which then would need more entries for the special characters.

A combination of both could still be an idea, however this would add more flash overhead but cover all problems. So you possibly have to decide been the current idea (more not visible delay) and a combination of both (more flash).

The best way to see if its a visual problem is to just let the beta testers try with their databases. What do you think of that?

**Comment by limpkin** [comment]
The LUT is currently used for the login menu.
It is 50ms & 17ms for your database, which we don't know how many credentials it has... how can we make a decision without that info?
Can you give a delay in ms per credential for a given first letter?
Once again, **we will not approve this PR based on a subjective feeling**

**Comment by NicoHood** [comment]
I get 17ms for 17 entries (in both directions). with an overhead of 8ms it seem that each credential takes about half a ms overhead. This means if you have 50 entries with a and 50 entries with b and are over a b entry you have about 58ms delay (from my calculations).

So would you rather go for a combined option between LUT and the way I implemented? If yes there are still two options:
* Start from the character as I got that currently to speed up non a-z chracters seach
* Always start from the beginning and search non a-z characters through whole flash

The last option fromt he above is also how `getParentNodeForLetter()` seems to work in the upper functions, as it only gives a good starting point to search for.

What would you prefer? Or would you enlarge the LUT or limit the start character to a-z?

**Comment by limpkin** [comment]
We'll think about it and get back to you.

**Comment by NicoHood** [comment]
If I add a check if the first letter is still the same as before (scrolling from "bugtracker" to "bios") then the information can be cached until you scrol to the next first character (a or c). This means in my example above if you scrol from a->b you have this 17ms delay. scrolling all b entries takes no time, as the information is cached (5ms, same as LUT). if you scrol from b->c it needs to load the first member of b and d again which will take a bit of time.

This can be optimized that you always keep the information for all 3 selected characters. this way if you scrol, only one direction needs to be updated. This means you can divide the time by 2 on average. The code for that will need some space though, but I have seperated the functions already really good. Thats possibly the best idea from my side so far.

**Comment by NicoHood** [comment]
@limpkin Was this fixed?

**Pull request closed without merging**
