### PR TITLE
login icon

### PR DESCRIPTION
**Pull request by reepush**

### CODE REVIEW

**Comment by limpkin** [comment]
login-icon files: any changes required to 

https://github.com/limpkin/mooltipass/blob/master/chrome_extension/manifest.json
https://github.com/limpkin/mooltipass/blob/master/chrome_extension/updateSafariExtension.sh
https://github.com/limpkin/mooltipass/blob/master/chrome_extension/updateCleanVersion.sh

?

**Comment by reepush** [comment]
@limpkin no, we copy files as a folder – no need to specify each file separately

**Comment by limpkin** [comment]
@reepush what about the manifest that specifies which files are used for content scripts?

**Comment by reepush** [comment]
```
    "ui/*"
```

**Comment by limpkin** [comment]
my bad... thanks!

**Pull request merged**
